### ISSUE TITLE
关于热点的2点建议

### ISSUE THREAD

**Issue by zhugunzi** [0730aa/hotspot#1]
1.8gen1支持双频热点,有些智能设备也需要2.4g 能否配置里面兼容 双频模式
2.热点能否加入 静态ip支持 ,目前重启后ip会变

**Comment by 0730aa** [comment]
> 1.8gen1支持双频热点,有些智能设备也需要2.4g 能否配置里面兼容 双频模式 2.热点能否加入 静态ip支持 ,目前重启后ip会变



1. 因为手上没有支持双频AP的设备，所以无法测试可行性，当然你乐意的话可以帮我测试这个命令： cmd wifi start-softap Hotspotplus wpa2 12345678 -b bridged 看看是否有效

2. 静态ip目前好像只是通过去api调整（即通过xposed来hook，比如那个 softAP ），强制用 ifconfig 调有问题，所以只能先用 LSPosed 那个模块实现，magisk 模块目前我也没办法实现

**Comment by 0730aa** [comment]
由于长时间不回复，我将关闭这个 issue
